services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "integrador2"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: